name:                logger2
version:             0.1.0.0
github:              "githubuser/logger2"
license:             BSD3
author:              "James Calrosn"
maintainer:          "jxxcarlsone@gmail.com"
copyright:           "2021 James Carlson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/logger#readme>

dependencies:
- base >= 4.7 && < 5
- MissingH
- text
- directory >= 1.3.6.0 && < 2
- monad-loops
- vector
- bytestring
- cassava
- hinduce-missingh

library:
  source-dirs: src

executables:
  logger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logger

tests:
  logger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logger
